"""Type stubs for the compiled C++ extension ``activationscope._C``.

Generated from the PYBIND11_MODULE bindings in ``csrc/hooks.cpp``.
"""

from typing import Dict
import torch

def register_max_hook(layer_name: str, output: torch.Tensor) -> None: ...
def register_min_hook(layer_name: str, output: torch.Tensor) -> None: ...
def register_mean_hook(layer_name: str, output: torch.Tensor) -> None: ...
def get_max_stats() -> Dict[str, float]: ...
def get_min_stats() -> Dict[str, float]: ...
def get_mean_stats() -> Dict[str, float]: ...
def clear_stats() -> None: ...
