#!/usr/bin/env python3
"""Generate .docker/docker-compose.yml from matrix.yml.

Usage:
    python utils/generate-compose.py                           # cpu default
    python utils/generate-compose.py --platform cu124          # cuda platform
    python utils/generate-compose.py --matrix /path/to/matrix.yml
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from matrix import load  # noqa: E402


COMPOSE_HEADER = """\
# Auto-generated by `python utils/generate-compose.py` — DO NOT EDIT.
"""

SVC_TEMPLATE = '''\
  {label}:
      build:
          context: ..
          dockerfile: .docker/Dockerfile
          args:
              PYTHON_VERSION: "{py}"
              PYTORCH_VERSION: "{torch}"
              PLATFORM: "{platform}"
      volumes:
          - ../activationscope:/src/activationscope
          - ../csrc:/src/csrc
          - ../tests:/src/tests
'''


def _label(py: str, torch: str, platform: str) -> str:
    return f"py{py.replace('.', '')}-torch{torch.replace('.', '')}-{platform}"


def generate(
    combos: list[dict], platform: str = "cpu",
) -> str:
    lines = [COMPOSE_HEADER, "services:"]

    for combo in combos:
        py = combo["python_version"]
        torch = combo["torch_version"]
        label = _label(py, torch, platform)
        lines.append(
            SVC_TEMPLATE.format(label=label, py=py, torch=torch, platform=platform)
        )

    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description="Generate .docker/docker-compose.yml from matrix.yml.")
    p.add_argument(
        "--matrix",
        default=os.path.join(os.path.dirname(__file__), "..", "matrix.yml"),
        help="Path to the matrix YAML file.",
    )
    p.add_argument(
        "--platform",
        default="cpu",
        help="Platform for PyTorch: cpu (default), cu121, cu124, etc.",
    )
    args = p.parse_args()

    combos = load(args.matrix)
    content = generate(combos, platform=args.platform)

    out_path = os.path.join(os.path.dirname(__file__), "..", ".docker", "docker-compose.yml")
    with open(out_path, "w") as f:
        f.write(content)

    print(f"Generated {out_path}  [platform={args.platform}]")


if __name__ == "__main__":
    main()
